/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdditionalInformationStep: typeof import('./../src/views/home/components/AdditionalInformationStep.vue')['default']
    AppointmentBookingSidebar: typeof import('./../src/views/home/components/AppointmentBookingSidebar.vue')['default']
    AppointmentStep: typeof import('./../src/views/home/components/AppointmentStep.vue')['default']
    CustomCalendar: typeof import('./../src/components/CustomCalendar.vue')['default']
    CustomSteps: typeof import('./../src/components/CustomSteps.vue')['default']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElText: typeof import('element-plus/es')['ElText']
    FinishStep: typeof import('./../src/views/home/components/FinishStep.vue')['default']
    IconArrowBack: typeof import('~icons/icon/arrow-back')['default']
    IconCarProfile: typeof import('~icons/icon/car-profile')['default']
    IconCart: typeof import('~icons/icon/cart')['default']
    IconCheck: typeof import('~icons/icon/check')['default']
    IconCheckCircle: typeof import('~icons/icon/check-circle')['default']
    IconCheckCircleFull: typeof import('~icons/icon/check-circle-full')['default']
    IconDelete: typeof import('~icons/icon/delete')['default']
    IconEvent: typeof import('~icons/icon/event')['default']
    IconFiles: typeof import('~icons/icon/files')['default']
    IconLeft: typeof import('~icons/icon/left')['default']
    IconMail: typeof import('~icons/icon/mail')['default']
    IconMapPin: typeof import('~icons/icon/map-pin')['default']
    IconMobile: typeof import('~icons/icon/mobile')['default']
    IconPhone: typeof import('~icons/icon/phone')['default']
    IconRight: typeof import('~icons/icon/right')['default']
    IconSearch: typeof import('~icons/icon/search')['default']
    IconUser: typeof import('~icons/icon/user')['default']
    MobileBookingOverlay: typeof import('./../src/views/home/components/MobileBookingOverlay.vue')['default']
    MobileCartOverlay: typeof import('./../src/views/home/components/MobileCartOverlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesStep: typeof import('./../src/views/home/components/ServicesStep.vue')['default']
    VehicleDataStep: typeof import('./../src/views/home/components/VehicleDataStep.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
